- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: isu6qportal (systemd)
      copy: src="../files/isu6qportal.service" dest="/etc/systemd/system/isu6qportal.service" owner=root mode=644
      register: service
    - name: systemctl daemon-reload
      command: systemctl daemon-reload
      when: service.changed
    - name: restart isu6qportal
      service: name=isu6qportal state=restarted enabled=true
      when: service.changed
